<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DF.Contracts" Version="1.0.0-pre-release4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.4" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.13" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Stripe.net" Version="50.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DF.PaymentService.Application\DF.PaymentService.Application.csproj" />
      <ProjectReference Include="..\DF.PaymentService.Domain\DF.PaymentService.Domain.csproj" />
    </ItemGroup>

</Project>
