default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: promo_user
  password: promoservice123!
  host: 127.0.0.1
  port: 3307

development:
  <<: *default
  database: PromoServiceDb
