<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>

        <PackageId>DF.Contracts</PackageId>
        <Version>1.0.1-pre-release5</Version>
        <Authors>Rostyslav</Authors>
        <PackageDescription>Shared contracts for DF microservices</PackageDescription>

        <RepositoryUrl>https://github.com/rostyslav/food-delivery-platform</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>


    <ItemGroup>
      <Folder Include="RPC\" />
        <Folder Include="RPC\Requests" />
        <Folder Include="RPC\Responses" />
        <Folder Include="RPC\Requests\MenuService" />
        <Folder Include="RPC\Requests\TrackingService" />
        <Folder Include="RPC\Requests\UserService" />
        <Folder Include="RPC\Responses\MenuService" />
        <Folder Include="RPC\Responses\TrackingService" />
        <Folder Include="RPC\Responses\UserService" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Gateway\" />
        <Folder Include="RPC\Requests\Accounts" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
    </ItemGroup>
    
</Project>
